export {
  type LinuxDistroSlug,
  type OsFamily,
  type OsPlatform,
  type ParsedOs,
  OS_PLATFORMS,
  detectOsFamily,
  ARCH_FAMILY_DISTROS,
  isArchFamilyDistro,
  isRhelFamilyDistro,
  osDisplayTitle,
  osDistroLabel,
  osFamilyLabel,
  osPrimaryBadgeLabel,
  osSummaryLine,
  parseOsDetail,
  parseOsRelease,
  rhelPlatformLabel,
} from "@fleet/os-display";
