import { randomBytes } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const jwt = randomBytes(48).toString("hex");
const seedPw = randomBytes(18).toString("base64url");

const env = `# Generated by npm run env:generate — do not commit (see .gitignore)
DATABASE_URL="postgresql://fleet:fleet@127.0.0.1:5432/fleet?schema=public"
REDIS_URL="redis://127.0.0.1:6379"
JWT_SECRET="${jwt}"
API_PORT=4000
NEXT_PUBLIC_API_URL="http://127.0.0.1:4000"
CORS_ORIGIN="http://localhost:3000,http://127.0.0.1:3000"

# Initial admin (used by npm run db:seed)
SEED_ADMIN_EMAIL="admin@localhost"
SEED_ADMIN_PASSWORD="${seedPw}"
`;

writeFileSync(path.join(root, ".env"), env, { encoding: "utf8" });
mkdirSync(path.join(root, "apps", "web"), { recursive: true });
writeFileSync(
  path.join(root, "apps", "web", ".env.local"),
  "NEXT_PUBLIC_API_URL=http://127.0.0.1:4000\n",
  { encoding: "utf8" },
);

console.log("Wrote", path.join(root, ".env"));
console.log("Wrote", path.join(root, "apps", "web", ".env.local"));
console.log("Initial admin: check SEED_ADMIN_EMAIL / SEED_ADMIN_PASSWORD in .env, then npm run db:seed");
