#!/usr/bin/env bash
# Optional agent mTLS CA + nginx snippet (does not break bearer-only agents).
#
#   sudo bash scripts/setup-fleet-mtls-ca.sh
#
# Controller .env:
#   FLEET_MTLS_CA_CERT=/etc/fleet/mtls/ca.crt
#   FLEET_MTLS_CA_KEY=/etc/fleet/mtls/ca.key
#   FLEET_AGENT_MTLS=optional
#
set -euo pipefail

MTLS_DIR="${FLEET_MTLS_DIR:-/etc/fleet/mtls}"
CA_CERT="${FLEET_MTLS_CA_CERT:-$MTLS_DIR/ca.crt}"
CA_KEY="${FLEET_MTLS_CA_KEY:-$MTLS_DIR/ca.key}"
NGINX_SNIP="${FLEET_MTLS_NGINX_SNIP:-/etc/nginx/fleet-mtls.conf}"

if [[ "$(id -u)" -ne 0 ]]; then
	echo "Run as root: sudo bash $0" >&2
	exit 1
fi

mkdir -p "$MTLS_DIR"
chmod 700 "$MTLS_DIR"

if [[ ! -f "$CA_CERT" || ! -f "$CA_KEY" ]]; then
	echo "--- generating Fleet agent client CA"
	openssl genrsa -out "$CA_KEY" 4096
	chmod 600 "$CA_KEY"
	openssl req -x509 -new -nodes -key "$CA_KEY" -sha256 -days 3650 \
		-out "$CA_CERT" \
		-subj "/CN=Fleet Agent mTLS CA/O=Fleet Control"
	chmod 644 "$CA_CERT"
fi

cat >"$NGINX_SNIP" <<'NGINX'
# Fleet optional agent mTLS (generated by setup-fleet-mtls-ca.sh)
ssl_verify_client optional;
ssl_client_certificate /etc/fleet/mtls/ca.crt;
proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
proxy_set_header X-SSL-Client-DN $ssl_client_s_dn;
NGINX

chmod 644 "$NGINX_SNIP"

ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"
if [[ -f "$ENV_FILE" ]]; then
	set_kv() {
		local k="$1" v="$2"
		if grep -q "^${k}=" "$ENV_FILE" 2>/dev/null; then
			sed -i "s|^${k}=.*|${k}=\"${v}\"|" "$ENV_FILE"
		else
			echo "${k}=\"${v}\"" >>"$ENV_FILE"
		fi
	}
	set_kv FLEET_MTLS_CA_CERT "$CA_CERT"
	set_kv FLEET_MTLS_CA_KEY "$CA_KEY"
	set_kv FLEET_AGENT_MTLS optional
fi

if command -v nginx >/dev/null 2>&1; then
	nginx -t && systemctl reload nginx
fi

echo ""
echo "Agent mTLS CA ready:"
echo "  CA cert: $CA_CERT"
echo "  nginx:   $NGINX_SNIP (optional client verify)"
echo ""
echo "New enrollments receive client certs when FLEET_AGENT_MTLS is not off."
echo "Existing agents keep working with bearer tokens only."
echo "Reload API: sudo systemctl restart fleet-api"
